=== ONSdigital/eq-schema-validator/schemas/questionnaire_v1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "mime_type",
    "schema_version",
    "data_version",
    "survey_id",
    "title",
    "sections",
    "theme",
    "metadata"
  ],
  "properties": {
    "eq_id": {
      "type": "string",
      "description": "Used in combination with the form_type to uniquely identify a questionnaire."
    },
    "form_type": {
      "type": "string",
      "description": "Used in combination with the eq_id to uniquely identify a questionnaire."
    },
    "mime_type": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "data_version": {
      "enum": [
        "0.0.1",
        "0.0.3"
      ]
    },
    "survey_id": {
      "type": "string",
      "description": "The ONS id of the survey derived from the inquiry code already in use for that survey.",
      "pattern": "^[0-9a-z]+$"
    },
    "session_timeout_in_seconds": {
      "description": "The amount of time in seconds before timing out a users session.",
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "theme": {
      "type": "string"
    },
    "legal_basis": {
      "type": "string"
    },
    "metadata": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "pattern": "^[a-zA-Z0-9-_]+$"
          },
          "type": {
            "type": "string",
            "enum": [
              "boolean",
              "date",
              "string",
              "uuid",
              "url"
            ]
          },
          "min_length": {
            "type": "integer",
            "description": "The minimum length of a string field",
            "minimum": 1
          },
          "max_length": {
            "type": "integer",
            "description": "The maximum length of a string field",
            "minimum": 1
          },
          "length": {
            "type": "integer",
            "description": "The length of a string field must be equal to this",
            "minimum": 0
          },
          "optional": {
            "description": "Whether an error should be raised if this field is not provided.",
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "type"
        ]
      }
    },
    "view_submitted_response": {
      "type": "object",
      "properties": {
        "enabled": {
          "description": "Whether or not answers are available after submission.",
          "type": "boolean"
        },
        "duration": {
          "description": "The amount of time in seconds submitted answers are available for.",
          "type": "integer"
        }
      },
      "required": [
        "enabled",
        "duration"
      ],
      "additionalProperties": false
    },
    "variables": {
      "type": "object",
      "properties": {
        "period": {
          "type": "string"
        }
      }
    },
    "navigation": {
      "type": "object",
      "description": "Used in conjunction with routing to take user through a survey. ",
      "properties": {
        "visible": {
          "type": "boolean"
        }
      }
    },
    "messages": {
      "$ref": "common_definitions.json#/messages"
    },
    "hub": {
      "type": "object",
      "properties": {
        "enabled": {
          "description": "Whether or not the hub and spoke pattern is enabled for this questionnaire.",
          "type": "boolean"
        },
        "required_completed_sections": {
          "description": "The sections that need to be complete prior to the hub displaying",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "enabled"
      ],
      "additionalProperties": false
    },
    "sections": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "type": "object",
        "properties": {
          "id": {
            "$ref": "common_definitions.json#/id"
          },
          "title": {
            "type": "string",
            "description": "Title used for the navigation container."
          },
          "title_from_answers": {
            "type": "array",
            "description": "Takes a list of answer ids. Title will be generated from answer values concatenated together with spaces."
          },
          "repeat": {
            "type": "object",
            "properties": {
              "for_list": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "for_list"
            ]
          },
          "groups": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "$ref": "common_definitions.json#/id"
                },
                "title": {
                  "type": "string"
                },
                "hide_in_navigation": {
                  "type": "boolean"
                },
                "skip_conditions": {
                  "$ref": "common_definitions.json#/skip_conditions"
                },
                "routing_rules": {
                  "$ref": "common_definitions.json#/routing_rules"
                },
                "blocks": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "oneOf": [{
                        "$ref": "blocks/answer_summary.json#/block"
                      },
                      {
                        "$ref": "blocks/calculated_summary.json#/block"
                      },
                      {
                        "$ref": "blocks/confirmation.json#/block"
                      },
                      {
                        "$ref": "blocks/confirmation_question.json#/block"
                      },
                      {
                        "$ref": "blocks/interstitial.json#/block"
                      },
                      {
                        "$ref": "blocks/introduction.json#/block"
                      },
                      {
                        "$ref": "blocks/list_collector.json#/block"
                      },
                      {
                        "$ref": "blocks/primary_person_list_collector.json#/block"
                      },
                      {
                        "$ref": "blocks/question.json#/block"
                      },
                      {
                        "$ref": "blocks/relationship_collector.json#/block"
                      },
                      {
                        "$ref": "blocks/summary.json#/block"
                      }
                    ]
                  }
                }
              },
              "additionalProperties": false,
              "required": [
                "id",
                "title",
                "blocks"
              ]
            }
          }
        },
        "required": [
          "id",
          "groups"
        ]
      }
    }
  },
  "additionalProperties": false
}

=== ONSdigital/eq-schema-validator/tests/schemas/valid/test_relationship_collector.json
{
    "mime_type": "application/json/ons/eq",
    "schema_version": "0.0.1",
    "data_version": "0.0.3",
    "survey_id": "0",
    "title": "Test Relationships",
    "theme": "default",
    "description": "A questionnaire to test capturing of relationships.",
    "messages": {},
    "metadata": [
        {
            "name": "user_id",
            "type": "string"
        },
        {
            "name": "period_id",
            "type": "string"
        },
        {
            "name": "ru_name",
            "type": "string"
        }
    ],
    "sections": [
        {
            "id": "section",
            "groups": [
                {
                    "id": "group",
                    "title": "Relationships",
                    "blocks": [
                        {
                            "type": "RelationshipCollector",
                            "id": "relationships",
                            "title": "This will iterate over the people list, capturing the one way relationships.",
                            "list": "people",
                            "question": {
                                "id": "relationship-question",
                                "type": "General",
                                "title": "Thinking of {first_person_name}, {second_person_name} is their <em>...</em>",
                                "answers": [
                                    {
                                        "id": "relationship-answer",
                                        "mandatory": true,
                                        "type": "Relationships",
                                        "playback": "{second_person_name} is {first_person_name} <em>â€¦</em>",
                                        "options": [
                                            {
                                                "value": "husband-or-wife",
                                                "label": "Husband or Wife",
                                                "relationship_title": "Thinking of {first_person_name}, {second_person_name} is their <em>husband or wife</em>",
                                                "relationship_playback": "{second_person_name} is {first_person_name} <em>husband or wife</em>"
                                            },
                                            {
                                                "value": "legally-registered-civil-partner",
                                                "label": "Legally registered civil partner",
                                                "relationship_title": "Thinking of {first_person_name}, {second_person_name} is their <em>legally registered civil partner</em>",
                                                "relationship_playback": "{second_person_name} is {first_person_name} <em>legally registered civil partner</em>"
                                            }
                                        ]
                                    }
                                ]
                            }
                        },
                        {
                            "type": "Confirmation",
                            "id": "confirmation",
                            "content": {
                                "title": "Thank you for your answers, do you wish to submit"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
